# Generated by Django 3.2.4 on 2021-06-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_ideas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='imgURL',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='price',
        ),
    ]
